# Creating object files
practica3.o: practica3.c  
	gcc -o practica3 practica3.c -I.


# To start over from scratch, type 'make clean'.  This
# removes the executable file, as well as old .o object
# files and *~ backup files:
#
clean: 
	$(RM) practica3 *.o *~

.PHONY: all practica3 clean
