# Generar l'executable
malloc_simple.so: malloc_simple.c  
	gcc -o malloc_simple.so malloc_simple.c struct.h -fPIC -g -shared 

# Comanda per utilitzar el meu malloc:
# export LD_PRELOAD=$PWD/malloc_simple.so



